### ISSUE TITLE
Setup dev environment instructions and scripts

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/LimbForge#1]

**Comment by matthova** [comment]
The dev environment is working, except that the folder structure for the STL files needs to be worked out. If you can, check out the README file and make sure that the steps work for you.

**Comment by andreasbastian** [comment]
Awesome, thanks for the instructions!

I followed them in my home directory and then in LimbForge, and in both
cases got the following errors.  Any ideas what I might be doing wrong?

andreass-mbp:LimbForge andreasbastian$ nvm install v5.10

v5.10.1 is already installed.

Now using node v5.10.1 (npm v3.8.3)

andreass-mbp:LimbForge andreasbastian$ nvm alias default v5.10

default -> v5.10 (-> v5.10.1)

andreass-mbp:LimbForge andreasbastian$ npm install

npm WARN enoent ENOENT: no such file or directory, open
'/Users/andreasbastian/package.json'

npm WARN andreasbastian No description

npm WARN andreasbastian No repository field.

npm WARN andreasbastian No README data

npm WARN andreasbastian No license field.

andreass-mbp:LimbForge andreasbastian$ npm start

npm ERR! Darwin 14.5.0

npm ERR! argv "/Users/andreasbastian/.nvm/versions/node/v5.10.1/bin/node"
"/Users/andreasbastian/.nvm/versions/node/v5.10.1/bin/npm" "start"

npm ERR! node v5.10.1

npm ERR! npm  v3.8.3

npm ERR! path /Users/andreasbastian/package.json

npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall open


npm ERR! enoent ENOENT: no such file or directory, open
'/Users/andreasbastian/package.json'

npm ERR! enoent ENOENT: no such file or directory, open
'/Users/andreasbastian/package.json'

npm ERR! enoent This is most likely not a problem with npm itself

npm ERR! enoent and is related to npm not being able to find a file.

npm ERR! enoent


npm ERR! Please include the following file with any support request:

npm ERR!     /Users/andreasbastian/Dropbox/e-NABLE/LimbForge/npm-debug.log

andreass-mbp:LimbForge andreasbastian$

**Comment by matthova** [comment]
@andreasbastian good point, I need to add a note saying that you need to be in the top level of this repo when running the commands.
Also, have you `git pull`ed down the most recent code? There should be a file called package.json in the top level of that repo
