### ISSUE TITLE
Device reviews and ratings

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/LimbForge#13]
As a user, I would like to know what other fabricators and recipients have learned from printing, fitting, and using devices from LimbForge.  Ideally, I would like to be able to look at a 0-5 star average rating and see written reviews (as with Amazon/Yelp) to help inform my decision about which design to print if there are multiple options for a given limb difference.  This would also be useful when beta testing designs.  Reviews and ratings would ideally also be accessible on the ECF Web Portal and could be viewed within LimbForge.

**Comment by kaitlynhova** [comment]
moved to https://github.com/e-nable/LimbForge/wiki/Feature-requests-(not-yet-rated)
