### ISSUE TITLE
Feature Requests (not yet ranked)

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/LimbForge#4]
Just starting a list of pieces of functionality that would be great to roll into LimbForge 

- [ ] TOS popup at begining of use
- [ ] Instructions for deriving measurements
- [ ] Feedback buttons for designs undergoing Beta testing
- [ ] Contextual dropdown menus for designs that have parts with more than one possible configuration (example:  RR has fingers with and without fingernails.  It would be great for users to be able to access configuration this way rather than by having the configurations as top-level "RR-with-nails" and "RR-without-nails" or for the different whippletree tensioners)
- [ ] Dropdown for machine type, populated with top five machines from 3DHubs trend report and a sixth "other"
- [ ] Function for creating Handathon packages that takes the parameters design type, and quantity and outputs a zip consisting of folders of print files for the design in the appropriate number of left and right configurations for the distribution of sizes derived from LimbForge's analytics, and amanifest with quantities of each size.  Idea that no matter how many designs are requested, the button will always deliver a distribution of sizes that matches what is typically downloaded from LimbForge.
- [ ] Add a "print with 3DHubs" button, as is seen on STL files on instructables.  Button should call handzipper to package the current configuration of STLs and send it to 3DHubs for local quoting.
- [ ] From Peter Binkley:  allow users to select which tolerances (tight, medium, loose) they would like to download.  Similar to machine-specific configuration, but different UI/UX-- maybe base decision on user feedback.
- [ ] Add a "include PDF assembly manual" check box that includes the appropriate assembly doc in the download package.
- [ ] Ability to load image of hands into the environment, calibrate the image, and overlay the design over the image to size.
- [ ] Add (contextual) buttons for ordering kits for each specific hand design.
- [ ] Add (contextual buttons that link to assembly information (say an instructable) for each hand design.
- [ ] Add button that links to design source files (if available) 

- [ ] Migrate to lettered sizing system (size A, B, C, D... etc) and pair with debossed size/version info on printed parts.

**Comment by mabuelhagag** [comment]
> TOS popup at begining of use
In #18

**Comment by kaitlynhova** [comment]
since this is a work in progress I moved it to a wiki page. Once each of these things are solidified we can make github issues for them individually: https://github.com/e-nable/LimbForge/wiki/Feature-requests-(not-yet-rated)
