### ISSUE TITLE
Geometry / CAD

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/LimbForge#7]
- [ ] Implement debossed lettering into thermogauntlets and palms for RR, TLRR.  Explore options for non-CAD designs. 
- [ ] Add Phoenix
- [ ] Add Osprey
- [ ] Add graphic thermogauntlet library
- [ ] Add labelling tags to pins on Phoenix, RR, etc.

Note:  will have dependencies on new UI/functional elements (buttons, links, dropdowns, etc)

**Comment by kaitlynhova** [comment]
moved to https://github.com/e-nable/LimbForge/wiki/Feature-requests-(not-yet-rated)
